baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "CARGO - for those who ship!"

[params]
# General information
author = "datenwelt"
description = "For those who deliver!"
copyright = "Released under the Apache 2.0 license"

# Repository
provider = "GitHub"
repo_url = "https://github.com/datenwelt/cargo-rest"

version = "0.1.0"
logo = "logo.png"
favicon = ""


custom_css = [
    "cargo.css"
  ]
  
[params.palette]
  primary = "lime"
  accent  = "blue grey"

[params.font]
  text = "Arial"
  code = "Cutive Mono"


[[menu.main]]
	name   = "Overview"
	url    = "overview/"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 20

[social]
	twitter = ""
	github  = "datenwelt"

